default:
  image: python:3.8-slim-buster

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - make test

deploy_heroku:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=drp25 --api-key=$HEROKU_API_KEY