# Generated by Django 3.0.6 on 2020-06-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='calendar',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='map',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='video',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='img_src',
            field=models.ImageField(null=True, upload_to='photos/2020/06/11'),
        ),
    ]
