# Generated by Django 3.0.6 on 2020-06-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='saved_schools',
            field=models.ManyToManyField(blank=True, to='app.School'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='useful_qas',
            field=models.ManyToManyField(blank=True, to='app.QA'),
        ),
    ]
