# Generated by Django 3.0.6 on 2020-06-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='recipient',
            new_name='recipient_school',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.SchoolAccount'),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.UserAccount'),
            preserve_default=False,
        ),
    ]
