# Generated by Django 3.0.6 on 2020-06-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200611_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='img_link',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
