# Generated by Django 3.0.6 on 2020-06-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200609_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='useful_qas',
            new_name='saved_qas',
        ),
        migrations.AlterField(
            model_name='school',
            name='img_src',
            field=models.ImageField(null=True, upload_to='photos/2020/06/10'),
        ),
    ]
