# Generated by Django 3.0.6 on 2020-06-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200603_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='image',
        ),
        migrations.AddField(
            model_name='school',
            name='img_src',
            field=models.ImageField(null=True, upload_to='photos/2020/06/04'),
        ),
    ]
