# Generated by Django 3.0.6 on 2020-06-08 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200604_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='recipient_school',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='app.School'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='img_src',
            field=models.ImageField(null=True, upload_to='photos/2020/06/08'),
        ),
    ]
