# Generated by Django 3.0.6 on 2020-06-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200604_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TY', 'Type'), ('EX', 'Extracurricular'), ('AM', 'Amenities'), ('OT', 'Other')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='img_src',
            field=models.ImageField(null=True, upload_to='photos/2020/06/09'),
        ),
        migrations.AddField(
            model_name='school',
            name='tags',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
