# Generated by Django 3.0.6 on 2020-06-11 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200611_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='answer_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='qa',
            name='question_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
