# Generated by Django 3.0.6 on 2020-06-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200611_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='sub_type',
            field=models.CharField(choices=[('General', 'General'), ('Sports', 'Sports'), ('Science', 'Science'), ('Art', 'Art')], default='General', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='img_src',
            field=models.ImageField(null=True, upload_to='photos/2020/06/12'),
        ),
    ]
