# Generated by Django 3.0.6 on 2020-06-13 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200612_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='img_src',
            field=models.ImageField(null=True, upload_to='photos/2020/06/13'),
        ),
        migrations.CreateModel(
            name='SchoolAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('school', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.School')),
            ],
        ),
    ]
