# Generated by Django 3.0.6 on 2020-06-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='tags',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
