# Generated by Django 3.0.6 on 2020-06-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_school_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('Type', 'Type'), ('Extracurricular', 'Extracurricular'), ('Amenities', 'Amenities'), ('Other', 'Other')], max_length=50),
        ),
    ]
