# Generated by Django 3.0.6 on 2020-06-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200614_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='ApplicantAccount',
        ),
    ]
