# Generated by Django 3.0.6 on 2020-06-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200615_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='img_src',
            field=models.ImageField(null=True, upload_to='photos/2020/06/16'),
        ),
    ]
