# Generated by Django 3.0.6 on 2020-06-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200616_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='prioritized_tags',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='school',
            name='img_src',
            field=models.ImageField(null=True, upload_to='photos/2020/06/17'),
        ),
    ]
