# Generated by Django 3.0.6 on 2020-06-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200617_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='map',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
